---
# tasks file for lthn-legacy
- name: Install Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openssl
    - ssl-cert

- name: Grab release latest binaries
  unarchive:
    src: "https://github.com/letheanVPN/blockchain-iz/releases/latest/download/linux.tar"
    dest: /usr/local/bin
    remote_src: true

- name: Allow chain RPC - ufw
  community.general.ufw:
    direction: in
    proto: "tcp"
    to_port: "48782"
    rule: allow
  ignore_errors: True

- name: Allow chain P2P - ufw
  community.general.ufw:
    direction: in
    proto: "tcp"
    to_port: "48772"
    rule: allow
  ignore_errors: True

- name: restart ufw
  service:
    name: ufw
    state: restarted
  ignore_errors: True

- name: Install PIP
  ansible.builtin.include_role:
    name: geerlingguy.pip

- name: Install Supervisor
  ansible.builtin.include_role:
    name: geerlingguy.supervisor

- name: Install LogRotate
  ansible.builtin.include_role:
    name: robertdebock.logrotate
